version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Setting up python directory"
      - mkdir -p python/lib/python3.8/site-packages
      - echo "Installing dependencies"
      - pip install -r requirements.txt -t python/lib/python3.8/site-packages/

  build:
    commands:
      - echo "Building the Lambda function package"
      # No need to zip lambda function code here

  post_build:
    commands:
      - echo "Publishing Lambda layer"
      - echo "Deploying the Lambda function"
      - aws lambda create-function --function-name my-function --runtime python3.8 --handler lambda_function.lambda_handler --role arn:aws:iam::123456789012:role/service-role/lambda-role --layers arn:aws:lambda:us-east-1:123456789012:layer:my-layer:$LAYER_VERSION --code S3Bucket=my-bucket-name,S3Key=lambda_function.zip

artifacts:
  files:
    - lambda_function.zip
