version: 0.2

phases:
  pre_build:
    commands:
      - echo Preparing to build
      - ls -al                   # List all files and directories in the root
      - ls -al Lambdafunction    # List all files and directories in Lambdafunction directory
      - cd Lambdafunction        # Change directory to Lambdafunction
      - echo "requests" > requirements.txt  # Create requirements.txt with 'requests' library
      - cat requirements.txt     # Output the contents of requirements.txt for verification
      - pip install -r requirements.txt -t .  # Install dependencies from requirements.txt into current directory
      - zip -r function.zip .    # Create function.zip containing Lambda function code and dependencies
      - cd ..                    # Change back to the root directory

  build:
    commands:
      - echo Building the Lambda function
      - aws s3 cp Lambdafunction/function.zip s3://github-lambda-layer/function.zip  # Upload function.zip to S3 bucket
      - aws lambda update-function-code --function-name github-to-lambda-layers --s3-bucket github-lambda-layer --s3-key function.zip  # Update Lambda function code

artifacts:
  files:
    - Lambdafunction/function.zip
