version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install requests -t .
      - zip -r function.zip .
      - aws s3 cp function.zip s3://your-s3-bucket/function.zip
  build:
    commands:
      - echo "Deploying Lambda function..."
      - aws lambda update-function-code --function-name github-to-lambda-layers --s3-bucket your-s3-bucket --s3-key function.zip
      - aws lambda update-function-configuration --function-name github-to-lambda-layers --layers arn:aws:lambda:us-east-1:123456789012:layer:my-layer:1
artifacts:
  files:
    - function.zip
