version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Setting up python directory"
      - mkdir -p python/lib/python3.8/site-packages
      - echo "Installing dependencies"
      - pip install -r requirements.txt -t python/lib/python3.8/site-packages/

  pre_build:
    commands:
      - echo "Zipping the dependencies for Lambda layer"
      - cd python/lib/python3.8/site-packages/
      - zip -r ../../../../../layer.zip .
      - cd -

  build:
    commands:
      - echo "Building the Lambda function package"
      - zip lambda_function.zip lambda_function.py

  post_build:
    commands:
      - echo "Deploying the Lambda layer"
      - aws lambda publish-layer-version --layer-name my-layer --zip-file fileb://layer.zip --compatible-runtimes python3.8
      - LAYER_VERSION=$(aws lambda list-layer-versions --layer-name my-layer --query 'LayerVersions[0].Version' --output text)
      - echo "Deploying the Lambda function"
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://lambda_function.zip
      - echo "Updating Lambda function configuration to use the new layer"
      - aws lambda update-function-configuration --function-name github-to-lambda-demo --layers arn:aws:lambda:$AWS_REGION:$AWS_ACCOUNT_ID:layer:my-layer:$LAYER_VERSION

artifacts:
  files:
    - layer.zip
    - lambda_function.zip
