version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install requests -t .
      - zip -r function.zip .

  build:
    commands:
      - echo "Deploying Lambda function..."
      - aws s3 cp function.zip s3://github-lambda-layer/function.zip
      - aws lambda add-layer-version-permission --layer-name LambdaInsightsExtension --version-number 53 --statement-id add-permission --principal '*' --action lambda:GetLayerVersion
      - aws lambda update-function-configuration --function-name github-to-lambda-layers --layers arn:aws:lambda:us-east-1:033914078355:layer:LambdaInsightsExtension:53
      - aws lambda update-function-code --function-name github-to-lambda-layers --s3-bucket github-lambda-layer --s3-key function.zip

artifacts:
  files:
    - function.zip
