version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install virtualenv
  pre_build:
    commands:
      - echo "Setting up virtual environment..."
      - python -m venv venv
      - source venv/bin/activate
      - echo "Installing package dependencies..."
      - mkdir -p python/lib/python3.10/site-packages
      - pip install -r requirements.txt -t python/lib/python3.10/site-packages/
  build:
    commands:
      - REGION="${AWS_REGION}"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "Zipping lambda function..."
      - zip function.zip lambda_function.py
      - echo "Zipping dependencies..."
      - zip -r layer.zip python/
      - echo "Uploading lambda function to S3..."
      - aws s3 cp function.zip s3://asconis-terraform-test/function.zip
      - echo "Updating lambda function..."
      - aws lambda update-function-code --function-name lambda_w_layers --s3-bucket github-lambda-layer --s3-key function.zip
      - echo "Uploading lambda layer to S3..."
      - aws s3 cp layer.zip s3://asconis-terraform-test/layer.zip
      - echo "Publishing lambda layer..."
      - LAYER_VERSION=$(aws lambda publish-layer-version --layer-name lambda_w_layers-dependencies --content S3Bucket=github-lambda-layer,S3Key=layer.zip --compatible-runtimes python3.10 --query Version --output text)
      - echo "Layer version = ${LAYER_VERSION}"
      - echo "Region = ${REGION}"
      - echo "Account Id = ${ACCOUNT_ID}"
      - echo "Updating lambda function layer..."
      - aws lambda update-function-configuration --function-name lambda_w_layers --layers arn:aws:lambda:${REGION}:${ACCOUNT_ID}:layer:lambda_w_layers-dependencies:${LAYER_VERSION}
      

artifacts:
  files:
    - function.zip
    - layer.zip